"""empty message

Revision ID: 737395db9acc
Revises: 8258e8c40052
Create Date: 2018-12-17 20:08:32.583812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737395db9acc'
down_revision = '8258e8c40052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'duration')
    # ### end Alembic commands ###
